### ISSUE TITLE
Specific data set or more general?

### ISSUE THREAD

**Issue by juliohm** [alstat/Bagyo.jl#2]
Is this package related to a specific data set that will not evolve over time or it is about a general API to download this type of data?

**Comment by alstat** [comment]
Hi @juliohm, this package aims to provide tools for the analysis of tropical cyclones affecting the PAR. It is therefore very specific (and not general, at least for now). Specific data are of interest, therefore, particularly those commonly used in literatures for understanding the cyclones, such as the JMA and JTWC data. I have to emphasize though that I am no expert in Geography/Climate. I am a statistician who recently got interested in typhoons.

To give you further context, the APIs available here (and those that will be addded) are based on the codes I used in the papers I've written so far.

- https://link.springer.com/article/10.1007/s41324-021-00415-4
- https://assets.researchsquare.com/files/rs-1335357/v1_covered.pdf?c=1647288832 (under review)

**Comment by juliohm** [comment]
Hi @alstat , that is great, thank you for putting the package together. It would be nice if you could elaborate on its scope in the README, explaining what it provides or aims to provide. Given that the name is not matching the name of the dataset, that will help users understand if this is a package for all kinds of data for cyclones and typhoons or just a specific one.

I am also a statistician by heart, you may find some of the following packages interesting:

- https://github.com/JuliaEarth/GeoStats.jl
- https://github.com/JuliaEarth/ExtremeStats.jl
- https://github.com/JuliaEarth/GeoTables.jl

**Comment by alstat** [comment]
Thank you for the support, @juliohm. Noted on your suggestions. I've been reading your GeoStats.jl and have used it in modeling soil suitability (using data from my R package ALUES), and I plan to present it in local conference here in the Philippines. Will definitely look and study your other packages. Thanks!

**Comment by juliohm** [comment]
That is lovely @alstat , please consider a citation in the conference proceedings, that helps a lot ❤️

**Comment by alstat** [comment]
Sure @juliohm!

**Comment by juliohm** [comment]
Marking as solved.
